name: flutter_first
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^0.1.2
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.2.0
  # 网络https://github.com/flutterchina/dio
  dio: ^2.1.13
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.21.0
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^0.2.6+1
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^4.0.2
  #eventbus
  event_bus: ^1.1.0
  #下拉刷新
  flutter_easyrefresh: ^1.2.7
  pull_to_refresh: ^1.5.4
  #加载网页
  webview_flutter: ^0.3.9+1
  #  flutter_webview_plugin: ^0.3.5
  flutter_swiper: ^1.1.5
  chewie: ^0.9.7
  video_player: ^0.10.1+6
  cached_network_image: ^1.1.1
  flukit: ^1.0.0
  date_utils: 0.1.0+2
  intl: 0.15.8
  fl_chart: 0.1.5
  esys_flutter_share: 1.0.2
  jpush_flutter: 0.0.11
  audioplayers: ^0.13.1
  scoped_model: ^1.0.1
  overlay_support: ^1.0.1
  url_launcher: ^4.0.1
  flutter_webview_plugin: ^0.2.1+2
  jaguar_flutter_asset: ^2.2.0
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^2.1.1
  crypto: 2.1.3
  shared_preferences: 0.5.3+4
  # 滚动字幕
  marquee: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/navigation/
    - assets/images/entry/
    - assets/images/login/
    - assets/images/consultation/
    - assets/images/mine/
    - mock/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
